### ISSUE TITLE
Can a `Roll`/`Unroll` contain `Nothing` as type variable?

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#16]
`Roll` and `Unroll` constructors are declared as:

```haskell
| Roll (Maybe TyVar) a | Unroll (Maybe TyVar) a
```

In what situations can the first field become a `Nothing`? I couldn't locate a single instance of such a case in the source code. It seems to always be a `Just`.

**Comment by jamescheney** [comment]
I think this may be a holdover from an early stage when we were writing programs directly in the core language, so that we were able to leave out the type annotations.  These seem to always be populated by the desugaring now, so can probably be omitted.  Roly may remember more.

**Comment by rolyp** [comment]
I remember their being populated by the desugaring, although not why they
needed to be optional :-/ It sounds like they can made non-optional, anyway.

(When we implement the slicing resugaring "properly", i.e. using the
original sugared expression to guide the backwards computation, we
presumably won't need these annotations anyway; we'll always be at the
right point in the original expression to recover them.)

**Comment by jstolarek** [comment]
Fixed on branch `js-resugaring`
