### ISSUE TITLE
Simplify "if" tracing

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#29]
Currently in `Trace` data type we have:

```haskell
  | TIfThen Trace Exp Exp Trace    -- ^ Take "then" branch of if
  | TIfElse Trace Exp Exp Trace    -- ^ Take "else" branch of if
```

`Exp` arguments don't seem to be used in any way.

**Comment by jamescheney** [comment]
Yes, they are an artifact of the "trace replay" that we have removed and not needed now.  Expressions in case and function call traces may also be superfluous now.

**Comment by jstolarek** [comment]
> Expressions in case and function call traces may also be superfluous now.

Indeed, they were - I removed them a while ago. Not sure why I didn't do the same with `if`s.
