### ISSUE TITLE
Update TraceTree

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#31]
`TraceTree` is a module that still is a bit mysterious to me. It looks to me that `TraceTree` data type records branching points during execution. This probably means that it should have two new constructors to track whether `with` block of try-with was executed or not. Not sure if it should have a new constructor to record that `if` condition raised an exception. Help appreciated.

**Comment by jstolarek** [comment]
I'm wondering if someone could take a look? If all goes well this will take about 5 minutes of thinking and about 10 minutes for me to fix.

**Comment by jamescheney** [comment]
That seems sensible.  I'm not sure this is on the critical path for the paper, though - are we relying on TraceTree for anything else right now?  If it is not much work to modify it so that it does something sensible, we can revisit that later.

**Comment by jstolarek** [comment]
> That seems sensible.

Um.. what exactly? Having constructors for `with` and `with-try`? What about exceptions in a condition of `if`?

> I'm not sure this is on the critical path for the paper, though

Probably not, but like I said - that's just a few minutes of work and would allow me to silence the warnings.

**Comment by jamescheney** [comment]
I'm happy with adding what seem like reasonable constructs to handle the
new features, to silence the warnings for now.

--James

**Comment by jstolarek** [comment]
Well, I can equally well silence the warnings with a flag. But I was actually thinking about solving this properly, ie. implementing the correct constructs, not just something that *seems* correct.

**Comment by jamescheney** [comment]
Given that this part of the code was fairly experimental, there isn't an a prioiri notion of "correctness" to respect - I had in mind defining a more efficient form of traces that could be used instead of the ones we are currently using but I don't think we worked out how to do slicing on them, for example.
