### ISSUE TITLE
leq/lub definitions for store labels

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#42]
I'm writing the definitions of `lub` and `leq` for new tracing constructs:

```haskell
           | TRef (Maybe StoreLabel) Trace | TDeref (Maybe StoreLabel) Trace
           | TAssign (Maybe StoreLabel) Trace Trace
```

I wonder what to do with store labels. I think guarding to ensure they are identical is the right thing to do.

**Comment by rolyp** [comment]
That sounds right.
