### ISSUE TITLE
Possible bug: Store invariants broken?

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#63]
The implementation of the `Store` logic might have a bug introduced by implementation of arrays:

```
Store { 
  { refs :: M.IntMap Value
  , arrs :: M.IntMap Array,
  , refCount :: Int
```
(Field names added for clarity.) The intention of `refCount` is to track the number of allocated references. So the invariant should be `M.Size refs = refCount`. This is invalidated by `storeCreateArr`:

```haskell
storeCreateArr :: Store -> Int -> Value -> (Store, StoreLabel)
storeCreateArr (Store refs arrs refCount) dim v =
    (Store refs (M.insert refCount (mkArray dim v) arrs) (refCount + 1),
     StoreLabel refCount)
```
So now the invariant is `M.Size refs + M.size arrs = refCount` and keys in `refs` and `arrs` are not consecutive integers.

I'm not sure if this causes any problems - needs deeper investigation.

**Comment by jamescheney** [comment]
I didn't see anywhere it was assumed that M.size refs == refCount.

**Comment by jstolarek** [comment]
Indeed, I think this is no longer needed in the current code. This was definitely required at some point in the past, but I think this invariant might have become obsolete when I refactored `Store` to be abstract outside of `Core` module. I definitely want to take a closer look at this later to make sure this is indeed correct.

**Comment by jstolarek** [comment]
This looks good.
